### ISSUE TITLE
Freeze when opening .yml file in Symfony compatibility mode

### ISSUE THREAD

**Issue by pulse00** [oyse/yedit#3]
When i open files with the `Use symfony compatibility mode` flag turned on and then open any yml file, eclipse freezes. Unfortunately there's no useful output in the .log.

It pretty much looks like if while opening the editor the yedit plugin hangs in an infinite loop somewhere.

Here's a yaml file that causes the issue (from the symfony2 standard edition):

``` yaml
imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Dubture\Bundle\SymfonyBlogBundle\SymfonyBlogBundle\Entity\User
```
